{
  "packages": [
    "apps/*",
    "components/*",
    "internals/*",
    "packages/*"
  ],
  "catalog": {
    "@tsconfig/node20": "^20.1.9",
    "@types/node": "^20.17.10",
    "chalk": "^5.6.2",
    "sass-embedded": "^1.97.3",
    "unbuild": "^3.6.1",
    "vue": "^3.5.28",
    "vue-tsc": "^3.2.4"
  }
}